### ISSUE TITLE
Restrict 3rd party application access?

### ISSUE THREAD

**Issue by ncoghlan** [default-to-open/about#1]
@romanofski @danc86 In setting up some permission grants for the BrisPy repos (specifically, GitHub Issue Mover), I noticed that this org and beaker-project.org were set to automatically allow access for any 3rd party services that individual contributors had authorised to use their account.

That doesn't seem like a good idea to me, so what do think about flicking the switch to require an org-level access grant as well as a user level one?

**Comment by romanofski** [comment]
Sounds fair to me. From what I see, most applications are mirrored only. The only half way "active" project is rpmgrill which arguably might be now better located on pagure.

**Comment by ncoghlan** [comment]
OK, I've flicked the switch for both this org and for https://github.com/beaker-project.
